### ISSUE TITLE
could not connect to sever

### ISSUE THREAD

**Issue by jessemoe** [johnnyzhang1992/imageSpider#1]
Traceback (most recent call last):
  File "E:\BaiduNetdiskDownload\cccsgo-imageSpider-master\imageSpider\update_wb.py", line 231, in <module>
    conn = psycopg2.connect(database=db_name, user=db_user, password=db_password, host="127.0.0.1", port="5432")
  File "E:\BaiduNetdiskDownload\python-3.7.0\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

**Comment by johnnyzhang1992** [comment]
这是连数据库的，估计是你本地没起相关服务吧。
